# ==============================================================================
# Application Information
# ==============================================================================
application.name=${project.name}
application.version=${project.version}

# ==============================================================================
# Application Specific Messages
# ==============================================================================
